apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: configrollouts.rollout.io
  labels:
    app.kubernetes.io/name: config-rollout
    app.kubernetes.io/part-of: rollout-poc
spec:
  group: rollout.io
  names:
    kind: ConfigRollout
    listKind: ConfigRolloutList
    plural: configrollouts
    singular: configrollout
    shortNames:
      - cr
      - configrollouts
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - configTemplate
                - rolloutStrategy
              properties:
                configTemplate:
                  type: object
                  description: "Configuration template to be deployed"
                  properties:
                    name:
                      type: string
                      description: "Name of the configuration template"
                    version:
                      type: string
                      description: "Version of the configuration template"
                    configData:
                      type: object
                      description: "Configuration data to be applied"
                      additionalProperties: true
                rolloutStrategy:
                  type: object
                  description: "Strategy for rolling out the configuration"
                  properties:
                    type:
                      type: string
                      enum: ["canary", "blue-green", "rolling"]
                      default: "canary"
                    canary:
                      type: object
                      description: "Canary rollout configuration"
                      properties:
                        steps:
                          type: array
                          description: "Steps for canary rollout"
                          items:
                            type: object
                            properties:
                              setWeight:
                                type: integer
                                format: int32
                                minimum: 0
                                maximum: 100
                                description: "Percentage of traffic to send to new version"
                              pause:
                                type: object
                                description: "Pause configuration"
                                properties:
                                  duration:
                                    type: string
                                    description: "Duration to pause (e.g., 30s, 5m)"
                                  manual:
                                    type: boolean
                                    description: "Whether to pause for manual approval"
                              analysis:
                                type: object
                                description: "Analysis configuration"
                                properties:
                                  templates:
                                    type: array
                                    description: "Analysis templates to use"
                                    items:
                                      type: object
                                      properties:
                                        templateName:
                                          type: string
                                          description: "Name of the analysis template"
                                        args:
                                          type: array
                                          description: "Arguments for the analysis template"
                                          items:
                                            type: object
                                            properties:
                                              name:
                                                type: string
                                              value:
                                                type: string
                targetDevices:
                  type: object
                  description: "Target devices for the rollout"
                  properties:
                    selector:
                      type: object
                      description: "Device selector"
                      properties:
                        matchLabels:
                          type: object
                          additionalProperties:
                            type: string
                        matchExpressions:
                          type: array
                          items:
                            type: object
                            properties:
                              key:
                                type: string
                              operator:
                                type: string
                                enum: ["In", "NotIn", "Exists", "DoesNotExist"]
                              values:
                                type: array
                                items:
                                  type: string
                    deviceList:
                      type: array
                      description: "Explicit list of device IDs"
                      items:
                        type: string
                webhook:
                  type: object
                  description: "Webhook configuration for validation"
                  properties:
                    url:
                      type: string
                      description: "Webhook URL for validation"
                    secret:
                      type: string
                      description: "Secret containing webhook authentication"
                    timeout:
                      type: string
                      description: "Webhook timeout"
                      default: "30s"
            status:
              type: object
              properties:
                phase:
                  type: string
                  enum: ["Pending", "Progressing", "Paused", "Healthy", "Degraded", "Failed"]
                  description: "Current phase of the rollout"
                message:
                  type: string
                  description: "Human-readable message about the current status"
                currentStep:
                  type: integer
                  format: int32
                  description: "Current step in the rollout"
                totalSteps:
                  type: integer
                  format: int32
                  description: "Total number of steps"
                progress:
                  type: string
                  description: "Progress percentage"
                lastTransitionTime:
                  type: string
                  format: date-time
                  description: "Last time the status changed"
                conditions:
                  type: array
                  description: "Current conditions of the rollout"
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                        enum: ["True", "False", "Unknown"]
                      lastTransitionTime:
                        type: string
                        format: date-time
                      reason:
                        type: string
                      message:
                        type: string
