apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: configrollouts.rollout.io
  labels:
    app.kubernetes.io/name: config-rollout
    app.kubernetes.io/part-of: rollout-poc
spec:
  group: rollout.io
  names:
    kind: ConfigRollout
    listKind: ConfigRolloutList
    plural: configrollouts
    singular: configrollout
    shortNames:
      - cr
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - config
                - targetDevices
              properties:
                config:
                  type: object
                  description: "Configuration to deploy"
                  properties:
                    name:
                      type: string
                      description: "Configuration name"
                    version:
                      type: string
                      description: "Configuration version"
                    data:
                      type: object
                      description: "Configuration data"
                      additionalProperties: true
                targetDevices:
                  type: array
                  description: "List of target device IDs"
                  items:
                    type: string
                rolloutSteps:
                  type: array
                  description: "Simple rollout steps"
                  items:
                    type: object
                    properties:
                      percentage:
                        type: integer
                        minimum: 0
                        maximum: 100
                        description: "Percentage of devices to update"
                      pauseDuration:
                        type: string
                        description: "Duration to pause (e.g., 30s, 5m)"
                        default: "30s"
            status:
              type: object
              properties:
                phase:
                  type: string
                  enum: ["Pending", "Progressing", "Completed", "Failed"]
                  description: "Current phase"
                message:
                  type: string
                  description: "Status message"
                currentStep:
                  type: integer
                  description: "Current step number"
                completedDevices:
                  type: array
                  items:
                    type: string
                  description: "List of devices that completed rollout"