apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: analysistemplates.rollout.io
  labels:
    app.kubernetes.io/name: analysis-template
    app.kubernetes.io/part-of: rollout-poc
spec:
  group: rollout.io
  names:
    kind: AnalysisTemplate
    listKind: AnalysisTemplateList
    plural: analysistemplates
    singular: analysistemplate
    shortNames:
      - at
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - validationUrl
              properties:
                validationUrl:
                  type: string
                  description: "URL for validation webhook"
                timeout:
                  type: string
                  description: "Validation timeout"
                  default: "30s"
                successCondition:
                  type: string
                  description: "Condition for success"
                  default: "result.status == 'success'"
            status:
              type: object
              properties:
                phase:
                  type: string
                  enum: ["Pending", "Running", "Successful", "Failed"]
                  description: "Current phase"
                message:
                  type: string
                  description: "Status message"