apiVersion: v1
kind: Service
metadata:
  name: canary-controller
  namespace: rollout-system
  labels:
    app.kubernetes.io/name: canary-controller
    app.kubernetes.io/part-of: rollout-poc
spec:
  selector:
    app.kubernetes.io/name: canary-controller
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  type: ClusterIP