apiVersion: rollout.io/v1alpha1
kind: ConfigRollout
metadata:
  name: simple-config-rollout
  namespace: rollout-apps
  labels:
    app.kubernetes.io/name: config-rollout
    app.kubernetes.io/part-of: rollout-poc
spec:
  config:
    name: "router-config"
    version: "v1.0.0"
    data:
      interfaces:
        - name: "eth0"
          ip: "192.168.1.1/24"
          status: "up"
      routing:
        - destination: "0.0.0.0/0"
          gateway: "192.168.1.254"
          interface: "eth0"
  targetDevices:
    - "router-001"
    - "router-002"
    - "router-003"
  rolloutSteps:
    - percentage: 25
      pauseDuration: "30s"
    - percentage: 50
      pauseDuration: "60s"
    - percentage: 100
      pauseDuration: "0s"