apiVersion: apps/v1
kind: Deployment
metadata:
  name: rollout-controller
  namespace: rollout-system
  labels:
    app.kubernetes.io/name: rollout-controller
    app.kubernetes.io/part-of: rollout-poc
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: rollout-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rollout-controller
    spec:
      containers:
      - name: controller
        image: golang:alpine
        command: ["sleep", "infinity"]
        ports:
        - containerPort: 8080
        env:
        - name: NAMESPACE
          value: "rollout-system"