apiVersion: dap.io/v1alpha1
kind: DeviceCohort
metadata:
  name: production-routers
  namespace: dap-rollouts
spec:
  devices:
  - deviceId: "router-001"
    deviceType: "router"
    site: "datacenter-east"
    status: "online"
  - deviceId: "router-002"
    deviceType: "router"
    site: "datacenter-east"
    status: "online"
  - deviceId: "router-003"
    deviceType: "router"
    site: "datacenter-west"
    status: "online"
  - deviceId: "router-004"
    deviceType: "router"
    site: "datacenter-west"
    status: "online"
  - deviceId: "router-005"
    deviceType: "router"
    site: "datacenter-central"
    status: "online"
  - deviceId: "router-006"
    deviceType: "router"
    site: "datacenter-central"
    status: "online"
  - deviceId: "router-007"
    deviceType: "router"
    site: "datacenter-central"
    status: "online"
  - deviceId: "router-008"
    deviceType: "router"
    site: "datacenter-central"
    status: "online"
  - deviceId: "router-009"
    deviceType: "router"
    site: "datacenter-central"
    status: "online"
  - deviceId: "router-010"
    deviceType: "router"
    site: "datacenter-central"
    status: "online"
  
  stages:
    canary:
      - "router-001"  # 1 device (10%)
    early:
      - "router-001"
      - "router-002"  # 2 devices (20%)
    broad:
      - "router-001"
      - "router-002"
      - "router-003"
      - "router-004"
      - "router-005"  # 5 devices (50%)
    full:
      - "router-001"
      - "router-002"
      - "router-003"
      - "router-004"
      - "router-005"
      - "router-006"
      - "router-007"
      - "router-008"
      - "router-009"
      - "router-010"  # All 10 devices (100%)
  
  filters:
    deviceTypes:
      - "router"
    sites:
      - "datacenter-east"
      - "datacenter-west"
      - "datacenter-central"
    status:
      - "online"
  
  metadata:
    description: "Production routers across all datacenters"
    tags:
      - "production"
      - "critical"
      - "routers"