apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: rollouts.argoproj.io
  labels:
    app.kubernetes.io/name: argo-rollouts
    app.kubernetes.io/part-of: argo-rollouts
spec:
  group: argoproj.io
  names:
    kind: Rollout
    listKind: RolloutList
    plural: rollouts
    singular: rollout
    shortNames:
      - ro
      - rollouts
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                replicas:
                  type: integer
                  format: int32
                  description: "Number of desired pods. This is a pointer to distinguish between explicit zero and not specified. Defaults to 1."
                selector:
                  type: object
                  description: "Label selector for pods. Existing ReplicaSets whose pods are selected by this will be the ones affected by this rollout."
                  properties:
                    matchExpressions:
                      type: array
                      description: "matchExpressions is a list of label selector requirements. The requirements are ANDed."
                      items:
                        type: object
                        properties:
                          key:
                            type: string
                            description: "key is the label key that the selector applies to."
                          operator:
                            type: string
                            description: "operator represents a key's relationship to a set of values. Valid operators are In, NotIn, Exists and DoesNotExist."
                          values:
                            type: array
                            description: "values is an array of string values. If the operator is In or NotIn, the values array must be non-empty. If the operator is Exists or DoesNotExist, the values array must be empty. This array is replaced during a strategic merge patch."
                            items:
                              type: string
                    matchLabels:
                      type: object
                      additionalProperties:
                        type: string
                      description: "matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels map is equivalent to an element of matchExpressions, whose key field is \"key\", the operator is \"In\", and the values array contains only \"value\". The requirements are ANDed."
                template:
                  type: object
                  description: "Template describes the pods that will be created."
                  properties:
                    metadata:
                      type: object
                      description: "Standard object's metadata."
                      properties:
                        annotations:
                          type: object
                          additionalProperties:
                            type: string
                          description: "Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata."
                        labels:
                          type: object
                          additionalProperties:
                            type: string
                          description: "Map of string keys and values that can be used to organize and categorize objects."
                        name:
                          type: string
                          description: "Name must be unique within a namespace."
                        namespace:
                          type: string
                          description: "Namespace defines the space within which each name must be unique."
                    spec:
                      type: object
                      description: "Specification of the desired behavior of the pod."
                      properties:
                        containers:
                          type: array
                          description: "List of containers belonging to the pod."
                          items:
                            type: object
                            properties:
                              name:
                                type: string
                                description: "Name of the container specified as a DNS_LABEL."
                              image:
                                type: string
                                description: "Docker image name."
                              env:
                                type: array
                                description: "List of environment variables to set in the container."
                                items:
                                  type: object
                                  properties:
                                    name:
                                      type: string
                                      description: "Name of the environment variable."
                                    value:
                                      type: string
                                      description: "Value of the environment variable."
                              resources:
                                type: object
                                description: "Compute Resources required by this container."
                                properties:
                                  limits:
                                    type: object
                                    additionalProperties:
                                      type: string
                                    description: "Limits describes the maximum amount of compute resources allowed."
                                  requests:
                                    type: object
                                    additionalProperties:
                                      type: string
                                    description: "Requests describes the minimum amount of compute resources required."
                        volumes:
                          type: array
                          description: "List of volumes that can be mounted by containers belonging to the pod."
                          items:
                            type: object
                            properties:
                              name:
                                type: string
                                description: "Volume's name. Must be a DNS_LABEL and unique within the pod."
                              configMap:
                                type: object
                                description: "ConfigMap represents a configMap that should populate this volume"
                                properties:
                                  name:
                                    type: string
                                    description: "Name of the referent."
                              secret:
                                type: object
                                description: "Secret represents a secret that should populate this volume"
                                properties:
                                  secretName:
                                    type: string
                                    description: "Name of the secret in the pod's namespace to use."
                strategy:
                  type: object
                  description: "Strategy describes how to replace existing pods with new ones."
                  properties:
                    canary:
                      type: object
                      description: "Canary strategy configuration"
                      properties:
                        steps:
                          type: array
                          description: "Steps define the order of actions to take"
                          items:
                            type: object
                            properties:
                              setWeight:
                                type: integer
                                format: int32
                                description: "SetWeight sets what percentage of the new version should receive traffic"
                              pause:
                                type: object
                                description: "Pause configuration"
                                properties:
                                  duration:
                                    type: string
                                    description: "Duration of the pause"
                              analysis:
                                type: object
                                description: "Analysis configuration"
                                properties:
                                  templates:
                                    type: array
                                    description: "Analysis templates to use"
                                    items:
                                      type: object
                                      properties:
                                        templateName:
                                          type: string
                                          description: "Name of the analysis template"
            status:
              type: object
              properties:
                observedGeneration:
                  type: string
                  description: "ObservedGeneration indicates the .metadata.generation that the controller observed"
                phase:
                  type: string
                  description: "Phase indicates the current phase of the rollout"
                message:
                  type: string
                  description: "Message provides details on why the rollout is in its current phase"
                replicas:
                  type: integer
                  format: int32
                  description: "Total number of non-terminated pods targeted by this rollout"
                readyReplicas:
                  type: integer
                  format: int32
                  description: "Total number of ready pods targeted by this rollout"
                availableReplicas:
                  type: integer
                  format: int32
                  description: "Total number of available pods targeted by this rollout"
                updatedReplicas:
                  type: integer
                  format: int32
                  description: "Total number of non-terminated pods targeted by this rollout that have the desired template spec"
                selector:
                  type: string
                  description: "Selector is a label query over pods that should match the replica count"